<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>WeiXiaochen&#39;s blog</title>
	<meta name="keywords" content=""/>
	<meta name="description" content=""/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1""/>
	
        <meta name="keywords" content="" />
    
	
		
			
<link rel="stylesheet" href="/css/highlight.css">

		
			
<link rel="stylesheet" href="/css/xc.css">

		
	
<meta name="generator" content="Hexo 5.4.0"></head>
<body>
	<header>
		<nav>
			
				<a href="/">首页</a> 
			
				<a href="/archives">归档</a> 
			
				<a href="/about">关于</a> 
			
				<a href="/link">友链</a> 
			
		</div>
	</header>
	<main>
		<article>
	
	
		
		
		<div>
			<img src="https://cdn.jsdelivr.net/gh/wxc0914/image/a3625c26bc8735174100f6d487763b06.png" alt="avatar"/>
			<div>
				<div>
					WeiXiaochen
				</div>
				<div>
					2021年04月05日
				</div>
			</div>
			
				
					<a class="btn" href="/categories/Java/">
						Java
					</a>
				
			
		</div>
		<h1>
			异常处理
		</h1>
		<div>
			<h3 id="异常"><a href="#异常" class="headerlink" title="异常"></a>异常</h3><h3 id="异常分类"><a href="#异常分类" class="headerlink" title="异常分类"></a>异常分类</h3><p>异常对象都是派生于Throwable类的一个实例，如果Java中内置的异常类不能够满足需求，用户还可以创建自己的异常类。</p>
<p><code>Throwable</code>的下一层被分为<code>Error</code>和<code>Exception</code>。<code>Exception</code>的下一层被分为<code>RuntimeException</code>和其他异常（比如：<code>IOException</code>）</p>
<p>Java语言规范将派生于Error类或RuntimeException类的所有异常称为非受查（unchecked）异常，所有的其他的异常称为受查（checked)异常</p>
<h3 id="抛出异常"><a href="#抛出异常" class="headerlink" title="抛出异常"></a>抛出异常</h3><p>一个方法不仅需要告诉编译器将要返回什么值，还要告诉编译器可能发生什么错误。方法应该在其首部声明所有可能抛出的异常。</p>
<p>什么情况下，必须抛出异常？</p>
<ul>
<li>调用一个抛出受查异常的方法</li>
<li>程序运行过程中发现错误，并且利用throw语句抛出一个受查异常。</li>
</ul>
<p>一个方法必须声明所有可能抛出的受查异常，而非受查异常要么不可控制（Error），要么就应该避免发生（RuntimeException）</p>
<p>子类方法中声明的受查异常不能比超类方法中声明的异常更通用。特别需要说明的是，如果超类方法没有抛出任何受查异常，子类也不能抛出任何受查异常。</p>
<p>如何抛出异常？</p>
<ul>
<li>找到一个合适的异常类</li>
<li>创建这个类的一个对象</li>
<li>将对象抛出<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">String <span class="title">readData</span><span class="params">(Scanner in)</span> <span class="keyword">throws</span> EOFException</span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">	...</span><br><span class="line">	<span class="keyword">while</span>(...) &#123;</span><br><span class="line">		<span class="keyword">if</span> (!in.hasNext()) &#123;</span><br><span class="line">			<span class="keyword">if</span> (n &lt; len) &#123;</span><br><span class="line">				String gripe = <span class="string">&quot;Content-length: &quot;</span> + len + <span class="string">&quot;, Received:&quot;</span> + n;</span><br><span class="line">				<span class="keyword">throw</span> <span class="keyword">new</span> EOFException(gripe);</span><br><span class="line">			&#125;</span><br><span class="line">		&#125;</span><br><span class="line">		...</span><br><span class="line">	&#125;</span><br><span class="line">	<span class="keyword">return</span> s;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="创建异常类"><a href="#创建异常类" class="headerlink" title="创建异常类"></a>创建异常类</h3>在程序中，可能会遇到任何标准异常都没有能够充分地 描述清楚的问题。在这种情况下，创建自己的异常类就是一件顺理成章的事情了。<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">FileFormatException</span> <span class="keyword">extends</span> <span class="title">IOException</span></span></span><br><span class="line"><span class="class"></span>&#123;</span><br><span class="line">	<span class="function"><span class="keyword">public</span> <span class="title">FileFormatException</span><span class="params">()</span></span>&#123;&#125;</span><br><span class="line">	<span class="function"><span class="keyword">public</span> <span class="title">FileFormatException</span><span class="params">(String gripe)</span></span></span><br><span class="line"><span class="function">	</span>&#123;</span><br><span class="line">		<span class="keyword">super</span> (gripe);</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></li>
</ul>
<p><strong>java.lang.Throwable</strong></p>
<ul>
<li><code>Throwable()</code> 构造一个新的Throwable对象，这个对象没有详细的描述信息。</li>
<li><code>Throwable(String message)</code> 构造一个新的throwable对象，这个对象带有特定的详细描述信息。习惯上，所有派生的异常类都支持一个默认的构造器和一个带有详细描述信息的构造器。</li>
<li><code>String getMessage()</code>获得Throwable对象的描述信息。</li>
</ul>
<h3 id="捕获异常"><a href="#捕获异常" class="headerlink" title="捕获异常"></a>捕获异常</h3><p>应该捕获那些知道如何处理的异常，而将那些不知道怎样处理的异常继续进行传递。要想捕获一个异常，必须设置try/catch语句块。如果在try语句块中的任何代码抛出了一个在catch子句中说明的异常类，那么程序将跳过try语句块的其余代码，执行catch子句中的处理器代码。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">publi <span class="keyword">void</span> <span class="title">read</span><span class="params">(String filename)</span></span></span><br><span class="line"><span class="function"></span>&#123;</span><br><span class="line">	<span class="keyword">try</span> &#123;</span><br><span class="line">		InputStream in = <span class="keyword">new</span> FileInputStream(filename);</span><br><span class="line">		<span class="keyword">int</span> b;</span><br><span class="line">		<span class="keyword">while</span> (b = in.read() != -<span class="number">1</span>) &#123;</span><br><span class="line">			process input</span><br><span class="line">		&#125;</span><br><span class="line">	&#125; <span class="keyword">catch</span>(IOException exception) &#123;</span><br><span class="line">		exception.printStackTrace();</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p><strong>注：</strong> 如果编写一个覆盖超类的方法，而这个方法又没有抛出异常，那么这个方法就必须捕获方法代码中出现的每一个受查异常。</p>
<p>在一个try语句块中可以捕获多个异常类型，并对不同类型的异常做出不同的处理。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">	code that might <span class="keyword">throw</span> exceptions</span><br><span class="line">&#125; <span class="keyword">catch</span>(FileNotFoundException e) &#123;</span><br><span class="line">	emergency action <span class="keyword">for</span> missing files</span><br><span class="line">&#125; <span class="keyword">catch</span>(UnknownHostException e) &#123;</span><br><span class="line">	emergency action <span class="keyword">for</span> unknown hosts</span><br><span class="line">&#125; <span class="keyword">catch</span>(IOException e) &#123;</span><br><span class="line">	emergency action <span class="keyword">for</span> all other I/O problems</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>在JavaSE7中，同一个catch子句中，可以==捕获多个异常类型==。只有当捕获的异常类型彼此之间不存在子类关系时才需要这个特性。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">	code that might <span class="keyword">throw</span> exceptions</span><br><span class="line">&#125; <span class="keyword">catch</span> (FileNotFoundException | UnknownHostException e) &#123;</span><br><span class="line">	emergency action <span class="keyword">for</span> missing files and unknown hosts </span><br><span class="line">&#125; <span class="keyword">catch</span>(IOException e) &#123;</span><br><span class="line">	emergency action <span class="keyword">for</span> all other I/O problems</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p><strong>注：</strong> 捕获多个异常时，异常变量隐含为==final变量==。所以，不能为e赋值。</p>
<h3 id="异常链"><a href="#异常链" class="headerlink" title="异常链"></a>异常链</h3><p>在catch子句中可以抛出一个异常，这样做的目的是改变异常的类型。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">	access the database</span><br><span class="line">&#125; <span class="keyword">catch</span> (SQLException) &#123;</span><br><span class="line">	<span class="keyword">throw</span> <span class="keyword">new</span> ServletException(<span class="string">&quot;database error: &quot;</span> + e.getMessage());</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>不过，可以有一种更好的方法，并且将原始异常设置为新异常的“原因”：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">	access the databse</span><br><span class="line">&#125; <span class="keyword">catch</span>(SQLException e) &#123;</span><br><span class="line">	Throwable se = <span class="keyword">new</span> ServletException(<span class="string">&quot;database error&quot;</span>);</span><br><span class="line">	se.initCase(e);</span><br><span class="line">	<span class="keyword">throw</span> se;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>当捕获到异常时，就可以使用下面这条语句重新获得到原始异常：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Throwable e = se.getCause()</span><br></pre></td></tr></table></figure>
<p>强烈建议使用这种包装技术，这样就可以让用户抛出子系统中的高级异常，而不会丢失原始异常的细节。</p>
<p>如果在一个方法中发生了一个受查异常，而不允许抛出它，那么包装技术就十分有用。我们可以捕获这个受查异常，并将它包装成一个运行时异常。</p>
<h3 id="finally"><a href="#finally" class="headerlink" title="finally"></a>finally</h3><p>当代码抛出一个异常时，并且方法获得了一些本地资源，那么就会产生资源回收问题。</p>
<p>在下面的示例中，程序将在所有情况下关闭文件。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line">InputStream in = <span class="keyword">new</span> FileInputStream(...);</span><br><span class="line"><span class="keyword">try</span> &#123; </span><br><span class="line">	...</span><br><span class="line">	code that might <span class="keyword">throw</span> exceptions</span><br><span class="line">	...</span><br><span class="line">&#125; <span class="keyword">catch</span> (IOException e) &#123;</span><br><span class="line">	...</span><br><span class="line">	show error message</span><br><span class="line">	...</span><br><span class="line">&#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">	...</span><br><span class="line">	in.close();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>这里，强烈建议解耦合try/catch和try/finally语句块。这样可以提高代码的清晰度。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line">InputStream in = ...;</span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">	<span class="keyword">try</span> &#123;</span><br><span class="line">		code that might <span class="keyword">throw</span> exceptions</span><br><span class="line">	&#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">		in.close();</span><br><span class="line">	&#125;</span><br><span class="line">&#125; <span class="keyword">catch</span>(IOException e) &#123;</span><br><span class="line">	show error message</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>内层的try语句块只有一个职责，就是确保关闭输入流。外层的try语句块就是确保报告出现的错误。这种设计方式不仅清楚，而且还具有一个功能，就是将会报告finally子句中出现的错误。</p>
<p>当finally子句包含return语句时，将会出现一种意想不到的结果。假设利用return语句从try语句块中退出。在方法返回前，finally子句的内容将被执行。如果finally子句中也有一个return语句，这个返回值将会覆盖原始的返回值。</p>
<h3 id="带资源的try语句"><a href="#带资源的try语句" class="headerlink" title="带资源的try语句"></a>带资源的try语句</h3><p>如果try块抛出一个异常，而且close方法也抛出一个异常，这就会带来一个难题。带资源的try语句可以很好地处理这种情况。原来的异常会重新抛出，而close方法 抛出的异常会被”被抑制”。这些异常将自动捕获，并由addSuppressed方法增加到原来的异常。可以调用getSuppressed方法，它会得到从close方法抛出并被抑制的异常列表。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> (Scanner in = <span class="keyword">new</span> Scanner(<span class="keyword">new</span> FinleInputStream(<span class="string">&quot;/usr/share/dict/words&quot;</span>), <span class="string">&quot;UTF-8&quot;</span>); </span><br><span class="line">	PrintWriter out = <span class="keyword">new</span> PrintWriter(<span class="string">&quot;out.txt&quot;</span>)) &#123;</span><br><span class="line">	<span class="keyword">while</span> (in.hasNext()) &#123;</span><br><span class="line">		out.println(in.next().toUpperCase());</span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>不论这个块如何退出，in和out都会关闭。</p>

		</div>
	
</article>

<div class="pagination">
	
		<a href="/page/18/">< 上一篇：多线程</a>
	
	
</div>
	</main>
	<footer></footer>
	
        
            
<script src="https://cdn.bootcdn.net/ajax/libs/instantclick/3.1.0/instantclick.min.js"></script>

        
            
<script src="/js/xc.js"></script>

        
    
</body>
</html>